apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMDAuMTIwLjIwNy42NzozMDUyOSI6eyJ1c2VybmFtZSI6IkNhc3RsZTk2IiwicGFzc3dvcmQiOiJkOGVlM2U5NzQ5N2ZjOWU5NjVlMWM0ZjQzZjliMjUwYmFiMzdjYTRlIiwiYXV0aCI6IlEyRnpkR3hsT1RZNlpEaGxaVE5sT1RjME9UZG1ZemxsT1RZMVpURmpOR1kwTTJZNVlqSTFNR0poWWpNM1kyRTBaUT09In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: polyglot-coach
type: kubernetes.io/dockerconfigjson
