apiVersion: v1
kind: Service
metadata:
  name: polyglot-coach
  namespace: polyglot-coach
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: http
      nodePort: 30011
      name: http
  selector:
    app: polyglot-coach
